name: getx_skeleton
version: 1.0.0+1
publish_to: none
description: start your project in the fastest way
environment: 
  sdk: '>=3.3.4 <4.0.0'

dependencies: 
  cupertino_icons: ^1.0.8
  get: ^4.6.6
  logger: ^2.3.0
  flutter_screenutil: ^5.9.3
  dio: ^5.4.3+1
  http_mock_adapter: ^0.6.1
  pretty_dio_logger: ^1.3.1
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  shared_preferences: ^2.2.3
  firebase_core: ^3.0.0
  firebase_messaging: ^15.0.0
  awesome_notifications: ^0.9.3+1
  flutter_launcher_icons: any
  change_app_package_name: any
  rename_app: 1.4.0
  flutter_svg: any
  flex_color_scheme: 7.3.1
  carousel_slider: 5.0.0
  google_fonts: 6.2.1
  flutter: 
    sdk: flutter

dev_dependencies: 
  mockito: any
  flutter_lints: any
  build_runner: any
  hive_generator: any
  pub_semver: ^2.1.4
  integration_test: 
    sdk: flutter
  flutter_test: 
    sdk: flutter

flutter_icons: 
  image_path: assets/images/app_icon.png
  android: true
  ios: true

flutter: 
  assets: 
    - assets/images/
    - assets/vectors/
    - assets/fonts/
  uses-material-design: true

